name = "neozpir-solid" # The name of your Pages project
compatibility_date = "2024-04-05" # Use a recent date

# D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "neozpir"
database_id = "f306269c-6433-4ed3-94b9-44574d24d9da"

[pages_build]
upload_dir = "dist"
build = "npm run build"
