name = "neozpir-solid" # The name of your Pages project
compatibility_date = "2024-04-05" # Use a recent date
main = "./worker/index.ts"

[vars]
NODE_ENV = "development"

[assets]
directory = "./dist/"
not_found_handling = "single-page-application"
binding = "ASSETS"
run_worker_first = [ "/api/*", "/sitemap.xml", "!/api/docs/*" ]

# D1 database binding
[[d1_databases]]
binding = "BLOG"
database_name = "neozpir-solid-blog"
database_id = "eeabd6cf-839f-4b84-bbdc-8f10f78649c2"

[env.production]
vars = { NODE_ENV = "production" }
# You would typically set these as secrets in production, but for demonstration:

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = false

